
create table locuslink
(locus_id text,
 locus_symbol text,
 refseq_NM text,
 refseq_NT text,
 unigene text,
 genbank_accession text,
 symbol_alias text,
 description text,
 omim text,
 location text,
 pfam_cdd text,
 pfam_id text,
 go_terms text,
 go_accessions text,
 pubmed text,
 refseq_XM text,
 refseq_NG text,
 swissprot_accession text,
 homologene text,
 refseq_NP text,
 chr1 text,
 start_position text,
 end_position text,
 orientation text,
 location_goldenpath text,
 location2 text,
 nb_exons text,
 chr2 text
);
